version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

